#!/bin/bash

if [ -z "$1" ]
then
	cp .vimrc ~/
	cp .tmux.conf ~/
	cp .bashrc ~/
  cp .zshrc ~/
	cp .p10k.zsh ~/
	cp .updatePush ~/
	cp config.conf ~/.config/neofetch/
	echo "All settings are up to date."
	echo "Files .vimrc .tmux.conf .bashrc .zshrc .p10k.zsh were updated (overwritten in ~/))."
fi



