#!/bin/bash

if [ -z "$1" ]
then
	cp .vimrc ~/
	cp .tmux.conf ~/
	cp .bashrc ~/
  cp .zshrc ~/
	cp .p10k.zsh ~/
	cp config.conf ~/.config/neofetch/
	echo "All settings are up to date."
	echo "Files .vimrc .tmux.conf .bashrc .zshrc were updated (overwritten in ~/))."
fi

if [ "$1" == "git" ]
then 
	git add -A
	git commit -m "Newest version of configFiles."
	git push
fi



